img = imread('roadway.jpg');
%img = imread('triangle.gif');
sigma=1;
n=5;
img1=GaussianFilter(img,sigma,n);
figure;
imshow(img1);
tlow=150;
thigh=255;
[x, y, mag, thresh, di]=SobelEdgeDetect(img1, tlow, thigh);
figure;
imshow(x);
title('Gx');
figure;
imshow(y);
title('Gy');
figure;
imshow(mag);
title('Mag');
figure;
imshow(thresh);
title('Thresholded');
figure;
imshow(di);
title('Direction');
[rowT, colT, dimT] = size(thresh);
thresh1=thresh((1+3):(rowT-4),(1+3):(colT-4),1);
figure;
imshow(thresh1);
title('Thresholded - Cropped');
v=HoughTransformLineDetection(thresh1);